name = "andika"
main = "./404.js"  # fake entry point to suppress warnings — not used
compatibility_date = "2025-08-14"

# This section is required for static uploads using --assets
[site]
bucket = "./dist"