// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func FAQs() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"sectionSize items-start pt-8 md:pt-36 bg-black text-white\"><div><h2 class=\"secondaryTitle bg-highlight3 p-10 mb-0 bg-center bg-100%\">FAQ</h2></div><div toggleElement class=\"w-full py-4\"><div class=\"flex justify-between items-center\"><div question class=\"font-montserrat font-medium mr-auto\">Where can I get this HTML template?</div><img src=\"dist/assets/logos/CaretRight.svg\" alt=\"\" class=\"transform transition-transform\"></div><div answer class=\"font-montserrat text-sm font-extralight pb-8 hidden\">You can download it on Gumroad.com</div></div><hr class=\"w-full bg-white\"><div toggleElement class=\"w-full py-4\"><div class=\"flex justify-between items-center\"><div question class=\"font-montserrat font-medium mr-auto\">Is this HTML template free?</div><img src=\"dist/assets/logos/CaretRight.svg\" alt=\"\" class=\"transform transition-transform\"></div><div answer class=\"font-montserrat text-sm font-extralight pb-8 hidden\">Yes! For you it is free.</div></div><hr class=\"w-full bg-white\"><div toggleElement class=\"w-full py-4\"><div class=\"flex justify-between items-center\"><div question class=\"font-montserrat font-medium mr-auto\">Am I awesome?</div><img src=\"dist/assets/logos/CaretRight.svg\" alt=\"\" class=\"transform transition-transform\"></div><div answer class=\"font-montserrat text-sm font-extralight pb-8 hidden\">Yes! No doubt about it.</div></div><hr class=\"w-full bg-white\"></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
