// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Features() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"features\" class=\"sectionSize bg-[#EFF6F6]\"><div><h2 class=\"secondaryTitle bg-underline3 bg-100%\">Features</h2></div><div class=\"md:grid md:grid-cols-2 md:grid-rows-2\"><div class=\"flex items-start my-6 mr-10\"><img src=\"/images/Heart.svg\" alt=\"\" class=\"h-7 mr-4\"><div><h3 class=\"font-semibold text-2xl\">Web & CLI Access</h3><p>Interact with your notes either through a web interface or directly via the CLI.</p></div></div><div class=\"flex items-start my-6 mr-10\"><img src=\"/images/Heart.svg\" alt=\"\" class=\"h-7 mr-4\"><div><h3 class=\"font-semibold text-2xl\">Version Control</h3><p>Every edit you save creates a snapshot, giving you a full version history for each note.</p></div></div><div class=\"flex items-start my-6 mr-10\"><img src=\"/images/Heart.svg\" alt=\"\" class=\"h-7 mr-4\"><div><h3 class=\"font-semibold text-2xl\">Easy Restore</h3><p>Restore any previous snapshot of a note quickly, ensuring no data is ever lost.</p></div></div><div class=\"flex items-start my-6 mr-10\"><img src=\"/images/Heart.svg\" alt=\"\" class=\"h-7 mr-4\"><div><h3 class=\"font-semibold text-2xl\">List & Search Notes</h3><p>Quickly list all notes or view individual note contents through API endpoints or CLI commands.</p></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
