// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Header() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header id=\"header\"><nav class=\"fixed flex justify-between py-6 w-full lg:px-48 md:px-12 px-4 content-center bg-secondary z-10\"><div class=\"flex items-center\"><img src=\"/public/images/note-logo.png\" alt=\"Logo\" class=\"h-4\"></div><ul class=\"font-montserrat items-center hidden md:flex\"><li class=\"mx-3 \"><a class=\"growing-underline\" href=\"howitworks\">How it works</a></li><li class=\"growing-underline mx-3\"><a href=\"features\">Features</a></li><li class=\"growing-underline mx-3\"><a href=\"pricing\">Pricing</a></li></ul><div class=\"font-montserrat hidden md:block\"><button class=\"mr-6\">Login</button> <button class=\"py-2 px-4 text-white bg-black rounded-3xl\">Signup</button></div><div id=\"showMenu\" class=\"md:hidden\"><img src=\"dist/assets/logos/Menu.svg\" alt=\"Menu icon\"></div></nav><div id=\"mobileNav\" class=\"hidden px-4 py-6 fixed top-0 left-0 h-full w-full bg-secondary z-20 animate-fade-in-down\"><div id=\"hideMenu\" class=\"flex justify-end\"><img src=\"dist/assets/logos/Cross.svg\" alt=\"\" class=\"h-16 w-16\"></div><ul class=\"font-montserrat flex flex-col mx-8 my-24 items-center text-3xl\"><li class=\"my-6\"><a href=\"howitworks\">How it works</a></li><li class=\"my-6\"><a href=\"features\">Features</a></li><li class=\"my-6\"><a href=\"pricing\">Pricing</a></li></ul></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
