// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Hero() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"pt-24 md:mt-0 md:h-screen flex flex-col justify-center text-center md:text-left md:flex-row md:justify-between md:items-center lg:px-48 md:px-12 px-4 bg-secondary\"><div class=\"md:flex-1 md:mr-10\"><h1 class=\"font-pt-serif text-5xl font-bold mb-7\">A headline for your <span class=\"bg-underline1 bg-left-bottom bg-no-repeat pb-2 bg-100%\">cool website</span></h1><p class=\"font-pt-serif font-normal mb-7\">Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum harum tempore consectetur voluptas, cumque nobis laboriosam voluptatem.</p><div class=\"font-montserrat\"><button class=\"bg-black px-6 py-4 rounded-lg border-2 border-black border-solid text-white mr-2 mb-2\">Call to action</button> <button class=\"px-6 py-4 border-2 border-black border-solid rounded-lg\">Secondary action</button></div></div><div class=\"flex justify-around md:block mt-8 md:mt-0 md:flex-1\"><div class=\"relative\"><img src=\"dist/assets/Highlight1.svg\" alt=\"\" class=\"absolute -top-16 -left-10\"></div><img src=\"dist/assets/MacBook Pro.png\" alt=\"Macbook\"><div class=\"relative\"><img src=\"dist/assets/Highlight2.svg\" alt=\"\" class=\"absolute -bottom-10 -right-6\"></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
