// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func HowItWorks() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"howItWorks\" class=\"bg-black text-white sectionSize\"><div><h2 class=\"secondaryTitle bg-underline2 bg-100%\">How it works</h2></div><div class=\"flex flex-col md:flex-row\"><div class=\"flex-1 mx-8 flex flex-col items-center my-4\"><div class=\"border-2 rounded-full bg-secondary text-black h-12 w-12 flex justify-center items-center mb-3\">1</div><h3 class=\" font-medium text-xl mb-2\">Create Notes</h3><p class=\"text-center \">Use Andika to instantly create trackable notes.</p></div><div class=\"flex-1 mx-8 flex flex-col items-center my-4\"><div class=\"border-2 rounded-full bg-secondary text-black h-12 w-12 flex justify-center items-center mb-3\">2</div><h3 class=\" font-medium text-xl mb-2\">Edit & Manage</h3><p class=\"text-center \">Append or overwrite note content seamlessly while maintaining version history.</p></div><div class=\"flex-1 mx-8 flex flex-col items-center my-4\"><div class=\"border-2 rounded-full bg-secondary text-black h-12 w-12 flex justify-center items-center mb-3\">3</div><h3 class=\" font-medium text-xl mb-2\">Snapshots & Restore</h3><p class=\"text-center \">Automatically track snapshots of notes and restore previous versions anytime.</p></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
